# -*- coding: utf-8 -*-
"""Forecast - ProductPrice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xwUx8K567w-C1vbHOCE8JLQ4PwLk2Yea
"""

## IGNORE SIMPLE WARNING -> MAKIN CODE CLEANER
import warnings
warnings.simplefilter('ignore')

!pip install pandas

!pip install pystan prophet

## IMPORTING NECESSARY DEPENDENCIES
import pandas as pd

## READING DATASET
dataset = pd.read_csv('dataset.csv')

dataset.head()

dataset.describe()

## GETTING UNIQUE DATA
print(dataset['Product'].unique())
print(dataset['Store'].unique())

## PREPROCESSING OF DATE
dataset['Year'] = dataset['Time Date'].apply(lambda x: str(x)[-4:])   ## extracting and getting last 4 digits representing year
dataset['Month'] = dataset['Time Date'].apply(lambda x: str(x)[-6:-4])  ## extracting and getting approp 2 digits representing month
dataset['Day'] = dataset['Time Date'].apply(lambda x: str(x)[:-6])  ## extracting and getting approp digits representing day
dataset['ds'] = pd.DatetimeIndex(dataset['Year'] + '-' + dataset['Month'] + '-' + dataset['Day'])  ## combining and setting up the date

dataset.dtypes

dataset.head()

## removing the unnecessary columns
dataset.drop(['Time Date', 'Product', 'Store', 'Year', 'Month', 'Day'], axis=1, inplace=True)

dataset.columns = ['y', 'ds']

dataset.head()

"""# **Model** **Training**"""

from prophet import Prophet  ## train quickly - accurate forecast

m = Prophet(interval_width=0.95, daily_seasonality=True)
model = m.fit(dataset)

model

"""# **Make Predictions**"""

future = model.make_future_dataframe(periods = 100, freq="D")
forecast= model.predict(future)
forecast.head()

forecast.tail()

dataset.tail()

forecast[['ds', 'yhat']]

## plotting
plot = model.plot(forecast)

plot2 = model.plot_components(forecast)